### ISSUE TITLE
How to compile prior to ulubis being included in quicklisp?

### ISSUE THREAD

**Issue by emacsomancer** [malcolmstill/ulubis#12]
You say that "the following will work pending inclusion of ulubis on quicklisp" - is there a way to get it working now?

**Comment by malcolmstill** [comment]
Off the top of my head, the easiest way would be to download:

- [cl-wayland](https://github.com/malcolmstill/cl-wayland)
- [cl-xkb](https://github.com/malcolmstill/cl-xkb)
- [cl-drm](https://github.com/malcolmstill/cl-drm)
- [cl-gbm](https://github.com/malcolmstill/cl-gbm)
- [cl-egl](https://github.com/malcolmstill/cl-egl)
- [cepl.drm-gbm](https://github.com/malcolmstill/cepl.drm-gbm)
- [cl-libinput](https://github.com/malcolmstill/cl-libinput)
- [ulubis-sdl](https://github.com/malcolmstill/ulubis-sdl)
- [ulubis-drm-gbm](https://github.com/malcolmstill/ulubis-drm-gbm)
- [ulubis](https://github.com/malcolmstill/ulubis/)

...and place them all in `quicklisp/local-projects`

You can then build by running sbcl or ccl (other implementations may work...please let me know if they do or do not):

```
[user@localhost ~] sbcl

* (ql:quickload :ulubis)

* (ulubis::build)
```

or

```
[user@localhost ~] sbcl

* (ql:quickload :ulubis)

* (ulubis::build-sdl)
```

Let me know if you have any difficulties and I apologise for it being so manual at the moment. Any feedback would be appreciated.

**Comment by emacsomancer** [comment]
Cheers. I'll give it a try soon.

**Comment by malcolmstill** [comment]
I believe it's now in quicklisp

**Comment by malcolmstill** [comment]
I've decided to start doing [releases](https://github.com/malcolmstill/ulubis/releases).

This should make it simple to install assuming you have SBCL and Quicklisp installed but doesn't pull any of my code off of Quicklisp.

**Comment by malcolmstill** [comment]
I'm moving away from the releases again. For the moment if a dependency is not on quicklisp, `local-projects/` it is until I figure out something better.
