### ISSUE TITLE
Doesn't build for me - CEPL issue

### ISSUE THREAD

**Issue by quicklisp** [malcolmstill/ulubis#32]
I get an error when building:

    ; caught ERROR:
    ;   READ error during COMPILE-FILE: Symbol "DEF-G->" not found in the CEPL package. Line: 253, Column: 13, File-Position: 9565 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/ulubis/24e20733e4584a5f3a0bb3f41be57735ea599f14/ulubis-20180123-git/render.lisp" {100E838323}>

**Comment by mschoenherr** [comment]
Cepls changelog says that they deprecated def-g-> in 2017/12. I will look into this issue and try to find out how we can get it building for everyone. (It doesn't build for me, which is said, because it seems like a great project!)

**Comment by malcolmstill** [comment]
Unfortunately replacing with `defpipeline-g` doesn't totally fix the build. After fixing those you come across this error https://github.com/cbaggers/cepl/blob/e0f740bf0bbe4008d8497091d933be4674a83abf/core/errors.lisp#L466.

I'm guessing this is because we initialise cepl with `(cepl:repl)` and this is starting cepl in its own thread. I'm not sure how to handle multiple threads with the latest changes or whether we can run everything in a single thread. Might have to get @cbaggers input.

**Comment by mschoenherr** [comment]
That sounds more complicated than expected. Thank you for the warning.

**Comment by cbaggers** [comment]
hey, sorry I'm late to this, I'm pretty bummed that this got broken as I was trying to keep the host api backwards compatible. Can wayland be set up on the same machine as one with X? If so I could try getting this running on mine.

CEPL should not be making any threads. It does set the initial context to be on the thread that the system was loaded with, if `(cepl:repl)` were then called from a different thread then there may be an issue. I'll raise a ticket to review how I handle this stuff again and in the mean time maybe I can fix the issue ulubis side.

**Comment by cbaggers** [comment]
https://github.com/cbaggers/cepl/issues/254

**Comment by malcolmstill** [comment]
Hi @cbaggers,

Yeah you can set up Wayland on a machine with X. With the ulubis-sdl build you can run ulubis on X (it just runs in a window).

I wonder if it's an issue the way the executables are built. I basically fire up SBCL (or CCL) load all of the dependencies and code and `save-lisp-and-die` an image. When the image starts up it does some initialisation and calls `cepl:repl` in what I understand to be the same thread, but perhaps there's something left over from the build stage that confuses it?

**Comment by cbaggers** [comment]
Oh yeah I bet that's it, last time I was shipping a binary was before the context & state caching so I bet it's an old context object..it would have nonsensical state by that point too as it would be holidng an old handles to threads.

**Comment by cbaggers** [comment]
Work and compiler have taken my time recently so I'm just getting to this now.

The binding of the thread to the cepl-context is done way too early and there are a bunch of things im not happy with in the initialization part of CEPL. I also think I will some functions to CEPL to be called just before save-lisp-and-die & just after resurrection; we can use these to handle any state wrangling that needs to be done.

**Comment by cbaggers** [comment]
Ok made some changes on a branch that let me build one of my projects as an exe and load it successfully. Next step is going to be getting ulubis-sdl working. Going to chill for a bit before streaming tonight so will look at this a bit after than and hopefully get back to it tomorrow.

**Comment by cbaggers** [comment]
https://github.com/malcolmstill/ulubis/pull/33
https://github.com/malcolmstill/ulubis-sdl/pull/2
with these I can get a ulubis to make a window in which I can see a cursor. I havent done any further testing but I'm going to call it a night.

I hope these help

**Comment by cbaggers** [comment]
Almost forgot, it probably also needs the feature/refactor-startup branch of CEPL. I'll try get that merged tomorrow.

**Comment by cbaggers** [comment]
The current issue I'm seeing is that there is an attempt to make a texture from a cairo surface, however the surface has width=0 height=0 and GL freaks out when given size 0 for any texture dimension

**Comment by cbaggers** [comment]
I've merged the cepl startup tweaks to master. I still will probably dig deeper into that code but those changes at least let save-lisp-and-die etc to work

**Comment by malcolmstill** [comment]
Thanks for all that @cbaggers, really great!

**Comment by cbaggers** [comment]
@malcolmstill no problem mate :)

**Comment by mschoenherr** [comment]
I acquired "newer" hardware and find this issue solved, good work! This can probably be closed now?

**Comment by mschoenherr** [comment]
I don't recall getting such an error, last time I tried. I will see, if I run into that error on the next possible occasion (which will probably be in two weeks time.)

**Comment by malcolmstill** [comment]
The binary has to be executed in the ulubis directory (it's looking for `cursor.png` in `assets/`).
