### ISSUE TITLE
 Symbol "INIT-EGL-WAYLAND" not found in the EGL package

### ISSUE THREAD

**Issue by budsbenzer** [malcolmstill/ulubis#57]
Hello, building ulubis (using sbcl) fails with the error
``` Symbol "INIT-EGL-WAYLAND" not found in the EGL package```
on line 124 of `ulubis-drm-gbm.lisp`.  As far as I can see, this symbol is not defined in `cl-egl.lisp`.  Is it maybe defined somewhere else, or am I missing something?

**Comment by malcolmstill** [comment]
I forgot to commit the cl-egl code. This should hopefully work for you now.

**Comment by budsbenzer** [comment]
Happens to the best of us. :)

Thanks for the reply, I'll try it out when I have the time.
