### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by ThomasBucaioni** [malcolmstill/ulubis#63]
Sbcl answers:
```
* 
debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
#<THREAD "main thread" RUNNING {1001878103}>:
  Package QL does not exist.

    Stream: #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100001C223}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE ] Use the current package, COMMON-LISP-USER.
  1: [RETRY    ] Retry finding the package.
  2: [USE-VALUE] Specify a different package
  3: [UNINTERN ] Read the symbol as uninterned.
  4: [SYMBOL   ] Specify a symbol to return
  5: [ABORT    ] Exit debugger, returning to top level.

(SB-IMPL::READER-FIND-PACKAGE "QL" #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100001C223}> T)
```
Any idea what went wrong? (Quicklisp is installed though...)

**Comment by PuercoPop** [comment]
@ThomasBucaioni Can you paste the contents of your sbclrc file? (`~/.sbclrc`). I'd guess that you installed quicklisp but didn't arrange for it to be loaded on start-up every time you start SBCL.

If you don't find

```lisp
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
```
add them. (Those should lines should have been added when you ran `ql:add-to-init-file`)

**Comment by ThomasBucaioni** [comment]
Indeed, I have no `~/.sbclrc`... But even adding these lines, sbcl still returns that ql doesn't exist: since I never ran `ql:add-to-init-file`, there are probably more things that I missed.
By the way, I just saw there's a channel on Gitter. Maybe it's more suitable to chat there?

**Comment by PuercoPop** [comment]
Gitter would work fine. As would #lisp@freenode as the issue is installing quicklisp. But you can follow the instructions at https://www.quicklisp.org/beta/#installation

```
$ sbcl --load quicklisp.lisp
* (quicklisp-quickstart:install)
* (ql:add-to-init-file)
```

**Comment by ThomasBucaioni** [comment]
It's one year I'm saying to myself I need to learn Lisp. Today is the day...
